#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000102c83154, pid=36327, tid=52483
#
# JRE version: OpenJDK Runtime Environment Zulu15.40+19-CA (15.0.7+4) (build 15.0.7+4-MTS)
# Java VM: OpenJDK 64-Bit Server VM Zulu15.40+19-CA (15.0.7+4-MTS, mixed mode, tiered, compressed oops, g1 gc, bsd-aarch64)
# Problematic frame:
# C  [python3.9+0x8b154]  dict_traverse+0x24
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://www.azul.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -Dfile.encoding=UTF8 -ea -Xmx1024m 

Host: MacBookPro18,1 arm64 1 MHz, 10 cores, 16G, Darwin 22.5.0
Time: Wed Aug 23 08:59:24 2023 KST elapsed time: 0.428068 seconds (0d 0h 0m 0s)

---------------  T H R E A D  ---------------

Current thread (0x00000003dd938200):  JavaThread "Python Reference Queue" daemon [_thread_in_native, id=52483, stack(0x00000004a524c000,0x00000004a544f000)]

Stack: [0x00000004a524c000,0x00000004a544f000],  sp=0x00000004a544e710,  free space=2057k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [python3.9+0x8b154]  dict_traverse+0x24
C  [python3.9+0x1b3640]  collect+0x2b4
C  [python3.9+0x1b4ae8]  PyGC_Collect+0x9c
C  [_jpype.cpython-39-darwin.so+0x1aa80]  JPGarbageCollection::triggered()+0x38
C  [_jpype.cpython-39-darwin.so+0x26684]  Java_org_jpype_ref_JPypeReferenceNative_wake+0x1c
j  org.jpype.ref.JPypeReferenceNative.wake()V+0
j  org.jpype.ref.JPypeReferenceQueue$Worker.run()V+42
j  java.lang.Thread.run()V+11 java.base@15.0.7
v  ~StubRoutines::call_stub
V  [libjvm.dylib+0x3e00a4]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)+0x324
V  [libjvm.dylib+0x3df17c]  JavaCalls::call_virtual(JavaValue*, Klass*, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0xf8
V  [libjvm.dylib+0x3df244]  JavaCalls::call_virtual(JavaValue*, Handle, Klass*, Symbol*, Symbol*, Thread*)+0x64
V  [libjvm.dylib+0x48e83c]  thread_entry(JavaThread*, Thread*)+0xbc
V  [libjvm.dylib+0x8cb660]  JavaThread::thread_main_inner()+0xa0
V  [libjvm.dylib+0x8c8b5c]  Thread::call_run()+0x88
V  [libjvm.dylib+0x711b78]  thread_native_entry(Thread*)+0x1d0
C  [libsystem_pthread.dylib+0x6fa8]  _pthread_start+0x94

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.jpype.ref.JPypeReferenceNative.wake()V+0
j  org.jpype.ref.JPypeReferenceQueue$Worker.run()V+42
j  java.lang.Thread.run()V+11 java.base@15.0.7
v  ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 2 (SEGV_ACCERR), si_addr: 0x000000016b210408

Register to memory mapping:

 x0=0x0000000168c216c0 points into unknown readable memory: 0x000000000000008b | 8b 00 00 00 00 00 00 00
 x1=0x0000000102dac8c4: visit_decref+0 in /Users/syshin/miniforge3/envs/tensorflow/bin/python3.9 at 0x0000000102bf8000
 x2=0x0000000168c216c0 points into unknown readable memory: 0x000000000000008b | 8b 00 00 00 00 00 00 00
 x3=0x0 is NULL
 x4=0x0 is NULL
 x5=0x0000ce0300000000 is an unknown value
 x6=0x0000000000000001 is an unknown value
 x7=0x0 is NULL
 x8=